version: '3'

services:
  web:
    build: .
    command: bash -c "
      uvicorn greens.main:app
      --host 0.0.0.0 --port 8989
      --lifespan=on --use-colors --loop uvloop --http httptools
      --log-config=log-conf.yaml
      --reload
      "
    volumes:
      - .:/app
    ports:
      - "8989:8989"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=root"
      - "MONGO_INITDB_ROOT_PASSWORD=example"
    command:
      mongod --quiet --logpath /dev/null