apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge-frontendp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontendp
        image: obscurebyron/challenge_frontend:latest
        ports:
        - containerPort: 3000

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge-authp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authp
  template:
    metadata:
      labels:
        app: authp  
    spec:
      containers:
      - name: authp
        image: obscurebyron/challenge_auth_api:latest
        env:
          - name: MONGODB_URL
            value: "mongodb://root:example@mongodb/?retryWrites=true&w=majority"
        ports:
        - containerPort: 8000

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge-articlesp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: articlesp
  template:
    metadata:
      labels:
        app: articlesp  
    spec:
      containers:
      - name: articlesp
        image: obscurebyron/challenge_articles_api:latest
        env:
          - name: DB_USER
            value: "postgres"
          - name: DB_NAME
            value: "postgres"
          - name: DB_HOST
            value: "postgresp"
          - name: DB_PORT
            value: "5432"
          - name: DB_PASSWORD
            value: "example"
          - name: APP_PORT
            value: "4000"
        ports:
        - containerPort: 4000       

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb  
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        env:
          - name: MONGO_INITDB_DATABASE
            value: "mongodb"
          - name: MONGO_INITDB_ROOT_USERNAME
            value: "root"
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: "example"
        ports:
        - containerPort: 27017      

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge-postgresdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresp
  template:
    metadata:
      labels:
        app: postgresp  
    spec:
      containers:
      - name: postgresp
        image: postgres:latest
        env:
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "postgres"
        ports:
        - containerPort: 5432                