// Code generated by ogen, DO NOT EDIT.
package ogent

type CreateArticleRes interface {
	createArticleRes()
}

type DeleteArticleRes interface {
	deleteArticleRes()
}

type ListArticleRes interface {
	listArticleRes()
}

type ReadArticleRes interface {
	readArticleRes()
}

type UpdateArticleRes interface {
	updateArticleRes()
}
